<?php
require_once __DIR__.'/includes/seguridad.php';require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/modulos_clinica.php';
exigirRoles(['admin','veterinario']);$pdo=getDB();asegurarModulosClinica($pdo);$mensaje='';$tipoMensaje='success';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validarCsrfModulo()){$mensaje='La sesión del formulario venció.';$tipoMensaje='danger';}
 else try{$accion=$_POST['accion']??'';
  if($accion==='ingresar'){$mascotaId=(int)($_POST['mascota_id']??0);$box=trim($_POST['box']??'');$motivo=trim($_POST['motivo']??'');$q=$pdo->prepare('SELECT nombre,dueno_id FROM mascotas WHERE id=:id');$q->execute([':id'=>$mascotaId]);$m=$q->fetch();if(!$m||!$box||!$motivo)throw new RuntimeException('Completa los datos de ingreso.');$q=$pdo->prepare('INSERT INTO hospitalizaciones (mascota_id,veterinario_id,box,motivo,indicaciones,fecha_ingreso) VALUES (:m,:v,:box,:motivo,:indicaciones,NOW())');$q->execute([':m'=>$mascotaId,':v'=>(int)$_SESSION['user_id'],':box'=>$box,':motivo'=>$motivo,':indicaciones'=>trim($_POST['indicaciones']??'')?:null]);$id=(int)$pdo->lastInsertId();crearNotificacion($pdo,(int)$m['dueno_id'],null,$m['nombre'].' ingresó a hospitalización','El equipo clínico registrará su evolución y te mantendrá informado.','hospitalizacion');registrarAuditoria($pdo,'hospitalizacion','ingreso',$id,$box);$mensaje='Ingreso registrado.';}
  elseif($accion==='alta'){$id=(int)($_POST['id']??0);if(!$id)throw new RuntimeException('Registro no válido.');$pdo->prepare("UPDATE hospitalizaciones SET estado='alta',fecha_alta=NOW() WHERE id=:id AND estado='hospitalizado'")->execute([':id'=>$id]);registrarAuditoria($pdo,'hospitalizacion','alta',$id);$mensaje='Alta registrada.';}
 }catch(Throwable $e){$mensaje=$e instanceof RuntimeException?$e->getMessage():'No fue posible guardar.';$tipoMensaje='danger';error_log('Hospitalización: '.$e->getMessage());}}
$registros=$pdo->query('SELECT h.*,m.nombre mascota,m.identificador,d.nombre dueno,d.telefono,u.nombre_completo veterinario FROM hospitalizaciones h JOIN mascotas m ON m.id=h.mascota_id JOIN duenos d ON d.id=m.dueno_id LEFT JOIN usuarios u ON u.id=h.veterinario_id ORDER BY (h.estado="hospitalizado") DESC,h.fecha_ingreso DESC')->fetchAll();$mascotas=$pdo->query('SELECT m.id,m.nombre,m.identificador,d.nombre dueno FROM mascotas m JOIN duenos d ON d.id=m.dueno_id ORDER BY m.nombre')->fetchAll();
$pageTitle='Hospitalización - VetClinic Pro';require_once __DIR__.'/includes/header.php';?>
<div class="page-header d-flex justify-content-between flex-wrap gap-3"><div><h3><i class="bi bi-hospital text-danger me-2"></i>Hospitalización</h3><p>Pacientes internados, box, indicaciones y altas.</p></div><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#ingresoModal"><i class="bi bi-plus-circle me-2"></i>Nuevo ingreso</button></div><?php if($mensaje):?><div class="alert alert-<?=e($tipoMensaje)?>"><?=e($mensaje)?></div><?php endif;?>
<div class="row g-3"><?php foreach($registros as $h):?><div class="col-md-6 col-xl-4"><div class="card card-stat h-100"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><span class="badge <?=$h['estado']==='hospitalizado'?'text-bg-danger':'text-bg-secondary'?>"><?=e(ucfirst($h['estado']))?></span><h5 class="mt-2 mb-1"><?=e($h['mascota'])?></h5><small class="text-muted"><?=e($h['dueno'].' · '.$h['telefono'])?></small></div><div class="text-end"><div class="small text-muted">BOX</div><strong class="fs-4"><?=e($h['box'])?></strong></div></div><hr><p><strong>Motivo:</strong> <?=e($h['motivo'])?></p><?php if($h['indicaciones']):?><div class="clinical-summary small"><?=nl2br(e($h['indicaciones']))?></div><?php endif;?><div class="small text-muted mt-3">Ingreso: <?=e(date('d/m/Y H:i',strtotime($h['fecha_ingreso'])))?> · <?=e($h['veterinario']?:'Sin asignar')?></div><?php if($h['estado']==='hospitalizado'):?><form method="post" class="mt-3"><input type="hidden" name="csrf_token" value="<?=e(csrfModulo())?>"><input type="hidden" name="accion" value="alta"><input type="hidden" name="id" value="<?=(int)$h['id']?>"><button class="btn btn-outline-success w-100"><i class="bi bi-check-circle me-1"></i>Registrar alta</button></form><?php endif;?></div></div></div><?php endforeach;?></div>
<div class="modal fade" id="ingresoModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Ingreso a hospitalización</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrfModulo())?>"><input type="hidden" name="accion" value="ingresar"><div class="modal-body"><div class="mb-3"><label class="form-label">Paciente</label><select name="mascota_id" class="form-select" required><option value="">Seleccionar...</option><?php foreach($mascotas as $m):?><option value="<?=(int)$m['id']?>"><?=e($m['nombre'].' · '.$m['dueno'])?></option><?php endforeach;?></select></div><div class="mb-3"><label class="form-label">Box / Jaula</label><input name="box" class="form-control" placeholder="Ej: Box 3" required></div><div class="mb-3"><label class="form-label">Motivo</label><textarea name="motivo" class="form-control" required></textarea></div><div><label class="form-label">Indicaciones del turno</label><textarea name="indicaciones" rows="4" class="form-control"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-danger">Registrar ingreso</button></div></form></div></div></div>
<?php require_once __DIR__.'/includes/footer.php';?>
