<?php
require_once __DIR__ . '/includes/seguridad.php';
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/modulos_clinica.php';
exigirRoles(['admin']);
$pdo=getDB(); asegurarModulosClinica($pdo); $mensaje=''; $tipoMensaje='success';
if ($_SERVER['REQUEST_METHOD']==='POST') {
 if (!validarCsrfModulo()) { $mensaje='La sesión del formulario venció.'; $tipoMensaje='danger'; }
 else try {
  $accion=$_POST['accion']??'';
  if ($accion==='guardar') {
   $id=(int)($_POST['id']??0); $nombre=trim($_POST['nombre']??''); $categoria=trim($_POST['categoria']??'');
   $stock=(float)($_POST['stock']??0); $minimo=(float)($_POST['stock_minimo']??0); $costo=(float)($_POST['costo_unitario']??0);
   if (!$nombre||!$categoria||$stock<0||$minimo<0||$costo<0) throw new RuntimeException('Revisa los datos del producto.');
   $datos=[':nombre'=>$nombre,':categoria'=>$categoria,':sku'=>trim($_POST['sku']??'')?:null,':stock'=>$stock,':minimo'=>$minimo,':unidad'=>trim($_POST['unidad']??'unidad'),':vence'=>($_POST['fecha_vencimiento']??'')?:null,':costo'=>$costo];
   if ($id) { $datos[':id']=$id; $pdo->prepare('UPDATE inventario SET nombre=:nombre,categoria=:categoria,sku=:sku,stock=:stock,stock_minimo=:minimo,unidad=:unidad,fecha_vencimiento=:vence,costo_unitario=:costo WHERE id=:id')->execute($datos); }
   else { $pdo->prepare('INSERT INTO inventario (nombre,categoria,sku,stock,stock_minimo,unidad,fecha_vencimiento,costo_unitario) VALUES (:nombre,:categoria,:sku,:stock,:minimo,:unidad,:vence,:costo)')->execute($datos); $id=(int)$pdo->lastInsertId(); }
   registrarAuditoria($pdo,'inventario',$id?'guardar':'crear',$id,$nombre); $mensaje='Producto guardado correctamente.';
  } elseif ($accion==='ajustar') {
   $id=(int)($_POST['id']??0); $cantidad=(float)($_POST['cantidad']??0); if(!$id||$cantidad==0) throw new RuntimeException('Indica una cantidad válida.');
   $pdo->prepare('UPDATE inventario SET stock=GREATEST(0,stock+:cantidad) WHERE id=:id')->execute([':cantidad'=>$cantidad,':id'=>$id]); registrarAuditoria($pdo,'inventario','ajustar_stock',$id,(string)$cantidad); $mensaje='Stock actualizado.';
  } elseif ($accion==='desactivar' || $accion==='reactivar') {
   $id=(int)($_POST['id']??0); if(!$id) throw new RuntimeException('Producto no válido.');
   $activo=$accion==='reactivar'?1:0;
   $stmt=$pdo->prepare('UPDATE inventario SET activo=:activo WHERE id=:id');$stmt->execute([':activo'=>$activo,':id'=>$id]);
   if(!$stmt->rowCount()) throw new RuntimeException('El producto no existe o ya estaba actualizado.');
   registrarAuditoria($pdo,'inventario',$accion,$id);$mensaje=$activo?'Producto restaurado.':'Producto retirado del inventario activo.';
  }
 } catch(Throwable $e){$mensaje=$e instanceof RuntimeException?$e->getMessage():'No fue posible guardar el producto.';$tipoMensaje='danger';error_log('Inventario: '.$e->getMessage());}
}
$mostrarInactivos=($_GET['vista']??'')==='inactivos';
$productosActivos=$pdo->query('SELECT * FROM inventario WHERE activo=1 ORDER BY (stock<=stock_minimo) DESC, fecha_vencimiento IS NULL, fecha_vencimiento, nombre')->fetchAll();
$productos=$mostrarInactivos?$pdo->query('SELECT * FROM inventario WHERE activo=0 ORDER BY nombre')->fetchAll():$productosActivos;
$bajo=count(array_filter($productosActivos,fn($p)=>(float)$p['stock']<=(float)$p['stock_minimo']));
$porVencer=count(array_filter($productosActivos,fn($p)=>$p['fecha_vencimiento']&&strtotime($p['fecha_vencimiento'])<=strtotime('+60 days')));
$valor=array_sum(array_map(fn($p)=>(float)$p['stock']*(float)$p['costo_unitario'],$productosActivos));
$pageTitle='Inventario - VetClinic Pro'; require_once __DIR__.'/includes/header.php';
?>
<div class="page-header d-flex justify-content-between flex-wrap gap-3"><div><h3><i class="bi bi-box-seam text-primary me-2"></i>Inventario</h3><p>Medicamentos, vacunas e insumos con alertas de reposición y vencimiento.</p></div><div class="d-flex gap-2"><a href="inventario.php<?= $mostrarInactivos?'':'?vista=inactivos' ?>" class="btn btn-outline-secondary"><i class="bi bi-archive me-1"></i><?= $mostrarInactivos?'Ver activos':'Ver inactivos' ?></a><?php if(!$mostrarInactivos):?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productoModal"><i class="bi bi-plus-circle me-2"></i>Nuevo producto</button><?php endif;?></div></div>
<?php if($mensaje):?><div class="alert alert-<?=e($tipoMensaje)?>"><?=e($mensaje)?></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="kpi-card kpi-danger"><div class="kpi-label">Stock bajo</div><div class="kpi-value"><?=$bajo?></div></div></div><div class="col-md-4"><div class="kpi-card kpi-warning"><div class="kpi-label">Vencen en 60 días</div><div class="kpi-value"><?=$porVencer?></div></div></div><div class="col-md-4"><div class="kpi-card kpi-success"><div class="kpi-label">Valor inventario</div><div class="kpi-value">$<?=number_format($valor,0,',','.')?></div></div></div></div>
<div class="card card-stat"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Producto</th><th>Categoría</th><th>Stock</th><th>Mínimo</th><th>Vencimiento</th><th>Costo</th><th>Ajuste</th><th>Acción</th></tr></thead><tbody><?php foreach($productos as $p): $bajoStock=(float)$p['stock']<=(float)$p['stock_minimo']; $vence=$p['fecha_vencimiento']&&strtotime($p['fecha_vencimiento'])<=strtotime('+60 days');?><tr class="<?=!$mostrarInactivos&&$bajoStock?'stock-danger':(!$mostrarInactivos&&$vence?'stock-warning':'')?>"><td><strong><?=e($p['nombre'])?></strong><div class="small text-muted"><?=e($p['sku']?:'Sin SKU')?></div></td><td><?=e($p['categoria'])?></td><td><strong><?=e((string)$p['stock'])?></strong> <?=e($p['unidad'])?></td><td><?=e((string)$p['stock_minimo'])?></td><td><?=$p['fecha_vencimiento']?e(date('d/m/Y',strtotime($p['fecha_vencimiento']))):'—'?></td><td>$<?=number_format((float)$p['costo_unitario'],0,',','.')?></td><td><?php if(!$mostrarInactivos):?><form method="post" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?=e(csrfModulo())?>"><input type="hidden" name="accion" value="ajustar"><input type="hidden" name="id" value="<?=(int)$p['id']?>"><input type="number" step="0.01" name="cantidad" class="form-control form-control-sm" style="width:90px" placeholder="+ / -"><button class="btn btn-sm btn-outline-primary"><i class="bi bi-check"></i></button></form><?php else:?><span class="text-muted">—</span><?php endif;?></td><td><form method="post" onsubmit="return confirm('<?= $mostrarInactivos?'¿Restaurar este producto?':'¿Retirar este producto del inventario activo?' ?>')"><input type="hidden" name="csrf_token" value="<?=e(csrfModulo())?>"><input type="hidden" name="accion" value="<?=$mostrarInactivos?'reactivar':'desactivar'?>"><input type="hidden" name="id" value="<?=(int)$p['id']?>"><button class="btn btn-sm btn-outline-<?=$mostrarInactivos?'success':'danger'?>" title="<?=$mostrarInactivos?'Restaurar':'Eliminar'?>"><i class="bi bi-<?=$mostrarInactivos?'arrow-counterclockwise':'trash'?>"></i></button></form></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="modal fade" id="productoModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Nuevo producto</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrfModulo())?>"><input type="hidden" name="accion" value="guardar"><div class="modal-body"><div class="row g-3"><div class="col-8"><label class="form-label">Nombre</label><input name="nombre" class="form-control" required></div><div class="col-4"><label class="form-label">SKU</label><input name="sku" class="form-control"></div><div class="col-6"><label class="form-label">Categoría</label><select name="categoria" class="form-select"><option>Medicamento</option><option>Vacuna</option><option>Insumo</option><option>Alimento</option></select></div><div class="col-6"><label class="form-label">Unidad</label><input name="unidad" value="unidad" class="form-control"></div><div class="col-4"><label class="form-label">Stock</label><input type="number" step="0.01" min="0" name="stock" value="0" class="form-control"></div><div class="col-4"><label class="form-label">Mínimo</label><input type="number" step="0.01" min="0" name="stock_minimo" value="0" class="form-control"></div><div class="col-4"><label class="form-label">Costo</label><input type="number" min="0" name="costo_unitario" value="0" class="form-control"></div><div class="col-12"><label class="form-label">Vencimiento</label><input type="date" name="fecha_vencimiento" class="form-control"></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>
<?php require_once __DIR__.'/includes/footer.php';?>
