<?php
require_once __DIR__.'/includes/seguridad.php'; require_once __DIR__.'/includes/db.php'; require_once __DIR__.'/includes/modulos_clinica.php';
exigirRoles(['admin','veterinario']); $pdo=getDB(); asegurarModulosClinica($pdo); $mensaje=''; $tipoMensaje='success';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validarCsrfModulo()){ $mensaje='La sesión del formulario venció.';$tipoMensaje='danger'; }
 else try{
  $mascotaId=(int)($_POST['mascota_id']??0); $medicamento=trim($_POST['medicamento']??''); $dosis=trim($_POST['dosis']??''); $frecuencia=trim($_POST['frecuencia']??''); $duracion=trim($_POST['duracion']??'');
  $q=$pdo->prepare('SELECT m.nombre,m.dueno_id FROM mascotas m WHERE m.id=:id');$q->execute([':id'=>$mascotaId]);$mascota=$q->fetch();
  if(!$mascota||!$medicamento||!$dosis||!$frecuencia||!$duracion)throw new RuntimeException('Completa todos los datos de la receta.');
  $q=$pdo->prepare('INSERT INTO recetas (mascota_id,veterinario_id,diagnostico,medicamento,dosis,frecuencia,duracion,indicaciones,fecha_emision) VALUES (:m,:v,:diag,:med,:dosis,:frecuencia,:duracion,:indicaciones,:fecha)');
  $q->execute([':m'=>$mascotaId,':v'=>(int)$_SESSION['user_id'],':diag'=>trim($_POST['diagnostico']??'')?:null,':med'=>$medicamento,':dosis'=>$dosis,':frecuencia'=>$frecuencia,':duracion'=>$duracion,':indicaciones'=>trim($_POST['indicaciones']??'')?:null,':fecha'=>($_POST['fecha_emision']??date('Y-m-d'))]);
  $id=(int)$pdo->lastInsertId(); crearNotificacion($pdo,(int)$mascota['dueno_id'],null,'Nueva receta para '.$mascota['nombre'],$medicamento.': '.$dosis.', '.$frecuencia.' durante '.$duracion.'.','receta'); registrarAuditoria($pdo,'recetas','crear',$id,$medicamento); $mensaje='Receta creada y disponible en la aplicación del dueño.';
 }catch(Throwable $e){$mensaje=$e instanceof RuntimeException?$e->getMessage():'No fue posible crear la receta.';$tipoMensaje='danger';error_log('Recetas: '.$e->getMessage());}
}
$recetas=$pdo->query('SELECT r.*,m.nombre mascota,m.identificador,d.nombre dueno,u.nombre_completo veterinario FROM recetas r JOIN mascotas m ON m.id=r.mascota_id JOIN duenos d ON d.id=m.dueno_id JOIN usuarios u ON u.id=r.veterinario_id ORDER BY r.fecha_emision DESC,r.id DESC LIMIT 100')->fetchAll();
$mascotas=$pdo->query('SELECT m.id,m.nombre,m.identificador,d.nombre dueno FROM mascotas m JOIN duenos d ON d.id=m.dueno_id ORDER BY m.nombre')->fetchAll();
$pageTitle='Recetas - VetClinic Pro';require_once __DIR__.'/includes/header.php';?>
<div class="page-header d-flex justify-content-between flex-wrap gap-3"><div><h3><i class="bi bi-prescription2 text-primary me-2"></i>Recetas</h3><p>Indicaciones estructuradas y visibles para el dueño.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#recetaModal"><i class="bi bi-plus-circle me-2"></i>Nueva receta</button></div>
<?php if($mensaje):?><div class="alert alert-<?=e($tipoMensaje)?>"><?=e($mensaje)?></div><?php endif;?>
<div class="row g-3"><?php if(!$recetas):?><div class="col-12"><div class="card card-stat"><div class="empty-state py-5"><i class="bi bi-prescription2"></i><p>Aún no hay recetas estructuradas.</p></div></div></div><?php endif;?><?php foreach($recetas as $r):?><div class="col-md-6 col-xl-4"><div class="card card-stat h-100"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><div class="small text-muted"><?=e(date('d/m/Y',strtotime($r['fecha_emision'])))?></div><h5 class="mb-0"><?=e($r['mascota'])?></h5><small><?=e($r['identificador'].' · '.$r['dueno'])?></small></div><i class="bi bi-capsule text-primary fs-3"></i></div><hr><h6 class="text-primary"><?=e($r['medicamento'])?></h6><div class="clinical-summary small"><div><strong>Dosis:</strong> <?=e($r['dosis'])?></div><div><strong>Frecuencia:</strong> <?=e($r['frecuencia'])?></div><div><strong>Duración:</strong> <?=e($r['duracion'])?></div></div><?php if($r['indicaciones']):?><p class="small mt-3 mb-2"><?=nl2br(e($r['indicaciones']))?></p><?php endif;?><div class="text-muted small mt-3"><i class="bi bi-person-badge me-1"></i><?=e($r['veterinario'])?></div></div></div></div><?php endforeach;?></div>
<div class="modal fade" id="recetaModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Nueva receta</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrfModulo())?>"><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Paciente</label><select name="mascota_id" class="form-select" required><option value="">Seleccionar...</option><?php foreach($mascotas as $m):?><option value="<?=(int)$m['id']?>"><?=e($m['nombre'].' · '.$m['dueno'].' · '.$m['identificador'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Fecha</label><input type="date" name="fecha_emision" value="<?=date('Y-m-d')?>" class="form-control" required></div><div class="col-12"><label class="form-label">Diagnóstico</label><input name="diagnostico" class="form-control"></div><div class="col-md-6"><label class="form-label">Medicamento</label><input name="medicamento" class="form-control" required></div><div class="col-md-6"><label class="form-label">Dosis</label><input name="dosis" placeholder="Ej: 1 comprimido" class="form-control" required></div><div class="col-md-6"><label class="form-label">Frecuencia</label><input name="frecuencia" placeholder="Ej: cada 12 horas" class="form-control" required></div><div class="col-md-6"><label class="form-label">Duración</label><input name="duracion" placeholder="Ej: 7 días" class="form-control" required></div><div class="col-12"><label class="form-label">Indicaciones</label><textarea name="indicaciones" rows="3" class="form-control"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Emitir receta</button></div></form></div></div></div>
<?php require_once __DIR__.'/includes/footer.php';?>
