<?php
require_once __DIR__.'/includes/seguridad.php';require_once __DIR__.'/includes/db.php';require_once __DIR__.'/includes/modulos_clinica.php';exigirRoles(['admin']);$pdo=getDB();asegurarModulosClinica($pdo);
$desde=$_GET['desde']??date('Y-m-01');$hasta=$_GET['hasta']??date('Y-m-d');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$desde))$desde=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$hasta))$hasta=date('Y-m-d');
$q=$pdo->prepare('SELECT DATE(fecha_hora) fecha,COUNT(*) total,SUM(estado="atendida") atendidas,SUM(estado="cancelada") canceladas FROM citas WHERE DATE(fecha_hora) BETWEEN :d AND :h GROUP BY DATE(fecha_hora) ORDER BY fecha');$q->execute([':d'=>$desde,':h'=>$hasta]);$citas=$q->fetchAll();
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN tipo='ingreso' THEN monto ELSE 0 END),0) ingresos,COALESCE(SUM(CASE WHEN tipo='egreso' THEN monto ELSE 0 END),0) egresos FROM caja WHERE fecha BETWEEN :d AND :h");$q->execute([':d'=>$desde,':h'=>$hasta]);$finanzas=$q->fetch()?:['ingresos'=>0,'egresos'=>0];
$diasPeriodo=max(1,(int)((strtotime($hasta)-strtotime($desde))/86400)+1);$anteriorHasta=date('Y-m-d',strtotime($desde.' -1 day'));$anteriorDesde=date('Y-m-d',strtotime($anteriorHasta.' -'.($diasPeriodo-1).' days'));$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN tipo='ingreso' THEN monto ELSE 0 END),0) ingresos FROM caja WHERE fecha BETWEEN :d AND :h");$q->execute([':d'=>$anteriorDesde,':h'=>$anteriorHasta]);$ingresosAnteriores=(float)$q->fetchColumn();$variacionIngresos=$ingresosAnteriores>0?round((((float)$finanzas['ingresos']-$ingresosAnteriores)/$ingresosAnteriores)*100):null;
$q=$pdo->prepare("SELECT COALESCE(u.nombre_completo,'Sin asignar') veterinario,COUNT(c.id) total,SUM(c.estado='atendida') atendidas FROM citas c LEFT JOIN usuarios u ON u.id=c.veterinario_id WHERE DATE(c.fecha_hora) BETWEEN :d AND :h GROUP BY c.veterinario_id,u.nombre_completo ORDER BY atendidas DESC");$q->execute([':d'=>$desde,':h'=>$hasta]);$rendimiento=$q->fetchAll();
$consultas=(int)$pdo->query("SELECT COUNT(*) FROM historial_clinico WHERE fecha_visita BETWEEN ".$pdo->quote($desde)." AND ".$pdo->quote($hasta))->fetchColumn();$vacunas=(int)$pdo->query("SELECT COUNT(*) FROM vacunas WHERE fecha_aplicacion BETWEEN ".$pdo->quote($desde)." AND ".$pdo->quote($hasta))->fetchColumn();$hospitalizados=(int)$pdo->query("SELECT COUNT(*) FROM hospitalizaciones WHERE estado='hospitalizado'")->fetchColumn();$stockBajo=(int)$pdo->query('SELECT COUNT(*) FROM inventario WHERE activo=1 AND stock<=stock_minimo')->fetchColumn();
if(($_GET['exportar']??'')==='csv'){header('Content-Type:text/csv;charset=UTF-8');header('Content-Disposition:attachment; filename="reporte_vetclinic_'.$desde.'_'.$hasta.'.csv"');$out=fopen('php://output','w');fputs($out,"\xEF\xBB\xBF");fputcsv($out,['Fecha','Citas','Atendidas','Canceladas'],';');foreach($citas as $r)fputcsv($out,[$r['fecha'],$r['total'],$r['atendidas'],$r['canceladas']],';');fclose($out);exit;}
$pageTitle='Reportes - VetClinic Pro';require_once __DIR__.'/includes/header.php';?>
<div class="page-header d-flex justify-content-between flex-wrap gap-3"><div><h3><i class="bi bi-bar-chart-line text-primary me-2"></i>Reportes</h3><p>Actividad clínica y financiera del período seleccionado.</p></div><div class="d-flex gap-2"><button class="btn btn-outline-danger" onclick="window.print()"><i class="bi bi-file-earmark-pdf me-2"></i>Imprimir / PDF</button><a class="btn btn-outline-success" href="?desde=<?=e($desde)?>&hasta=<?=e($hasta)?>&exportar=csv"><i class="bi bi-file-earmark-spreadsheet me-2"></i>Exportar CSV</a></div></div>
<div class="card card-stat mb-4"><div class="card-body"><form class="module-toolbar"><label class="form-label mb-0">Desde</label><input type="date" name="desde" value="<?=e($desde)?>" class="form-control w-auto"><label class="form-label mb-0">Hasta</label><input type="date" name="hasta" value="<?=e($hasta)?>" class="form-control w-auto"><button class="btn btn-primary">Actualizar</button></form></div></div>
<div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="kpi-card kpi-primary"><div class="kpi-label">Consultas</div><div class="kpi-value"><?=$consultas?></div></div></div><div class="col-6 col-xl-3"><div class="kpi-card kpi-success"><div class="kpi-label">Vacunas</div><div class="kpi-value"><?=$vacunas?></div></div></div><div class="col-6 col-xl-3"><div class="kpi-card kpi-danger"><div class="kpi-label">Hospitalizados</div><div class="kpi-value"><?=$hospitalizados?></div></div></div><div class="col-6 col-xl-3"><div class="kpi-card kpi-warning"><div class="kpi-label">Stock bajo</div><div class="kpi-value"><?=$stockBajo?></div></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card card-stat h-100"><div class="card-body p-4"><h6 class="fw-bold">Resumen financiero</h6><div class="clinical-summary mt-3"><div class="d-flex justify-content-between mb-3"><span>Ingresos</span><strong class="text-success">$<?=number_format((float)$finanzas['ingresos'],0,',','.')?></strong></div><div class="d-flex justify-content-between mb-3"><span>Variación anterior</span><strong class="<?=($variacionIngresos??0)>=0?'text-success':'text-danger'?>"><?=$variacionIngresos===null?'Sin referencia':(($variacionIngresos>0?'+':'').$variacionIngresos.'%')?></strong></div><div class="d-flex justify-content-between mb-3"><span>Egresos</span><strong class="text-danger">$<?=number_format((float)$finanzas['egresos'],0,',','.')?></strong></div><div class="d-flex justify-content-between"><span>Balance</span><strong>$<?=number_format((float)$finanzas['ingresos']-(float)$finanzas['egresos'],0,',','.')?></strong></div></div></div></div></div><div class="col-lg-7"><div class="card card-stat"><div class="card-body p-4"><h6 class="fw-bold">Citas por día</h6><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Fecha</th><th>Total</th><th>Atendidas</th><th>Canceladas</th></tr></thead><tbody><?php foreach($citas as $r):?><tr><td><?=e(date('d/m/Y',strtotime($r['fecha'])))?></td><td><?=$r['total']?></td><td class="text-success"><?=$r['atendidas']?></td><td class="text-danger"><?=$r['canceladas']?></td></tr><?php endforeach;?></tbody></table></div></div></div></div><div class="col-12"><div class="card card-stat"><div class="card-body p-4"><h6 class="fw-bold">Actividad por veterinario</h6><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Veterinario</th><th>Citas asignadas</th><th>Atendidas</th><th>Tasa de atención</th></tr></thead><tbody><?php foreach($rendimiento as $r):?><tr><td><?=e($r['veterinario'])?></td><td><?=(int)$r['total']?></td><td><?=(int)$r['atendidas']?></td><td><?=($r['total']?round(((int)$r['atendidas']/(int)$r['total'])*100):0)?>%</td></tr><?php endforeach;?></tbody></table></div></div></div></div></div>
<?php require_once __DIR__.'/includes/footer.php';?>
